dist: bionic
addons:
  apt:
    packages:
      - cmake
      - python3.6-dev
      - python3.6-venv
matrix:
  fast_finish: true
  include:
    - language: rust
      rust: stable
      os: osx
      osx_image: xcode10.1
    - language: rust
      os: linux
      rust: stable

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      python3.6 -m venv venv
      source venv/bin/activate
      pip install tensorflow virtualenv pytest
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      python3 -m venv venv
      source venv/bin/activate
      pip install tensorflow virtualenv pytest
    fi

script: ci/script.sh