dist: bionic
addons:
  apt:
    packages:
      - cmake

matrix:
  fast_finish: true
  include:
    - language: rust
      rust: stable
      os: osx
      osx_image: xcode10.1
      env:
        - TF_VER=1.14
    - language: rust
      rust: stable
      os: osx
      osx_image: xcode10.1
      env:
        - TF_VER=2
    - language: python
      python: 3.6
      addons:
        apt:
          packages:
            - g++-4.8
      env:
        - CC=gcc-4.8
        - CXX=g++-4.8
        - TF_VER=1.14
    - language: python
      python: 3.7
      env:
        - TF_VER=1.14
    - language: python
      python: 3.7
      addons:
        apt:
          packages:
            - g++-8
      env:
        - TF_VER=2

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- -y
      source $HOME/.cargo/env
      pip install tensorflow==$TF_VER virtualenv pytest
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      python3 -m venv venv
      source venv/bin/activate
      pip install tensorflow==$TF_VER virtualenv pytest
    fi

script: ci/script.sh